# 開発環境(djangoとpsql)

version: '3'  # Docker Composeのバージョン

services:
  web:
    build:
      context: ./web            # ディレクトリ
      dockerfile: Dockerfile    # ファイル名
    command: bash -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./web/portfolio:/code  # Djangoプロジェクトのディレクトリをコンテナ内の/codeにバインド
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:10.4-alpine
    volumes:
        - db_data:/var/lib/postgresql/data    # ボリュームなので`./`をつけない
    restart: always # コンテナが停止したときに再起動
    env_file: ./db/.env.db
    ports:
      - "5432:5432"

volumes:
  db_data: