# 本番環境(django, psql, gunicorn, nginx)

version: '3'  # Docker Composeのバージョン

services:
  web:
    build:
      context: ./web            # ディレクトリ
      dockerfile: Dockerfile    # ファイル名
    volumes:
      - static_volume:/code/web/static  # volumeとcollectstaticしたディレクトリをマウント
      - media_volume:/code/web/media
    command: bash -c "python manage.py collectstatic --noinput && 
      python manage.py migrate && 
      gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    expose: # 直接リクエストすることがなくなるためportsをexposeに変更
      - 8000
    env_file: ./web/portfolio/.env  # 環境変数を指定
    depends_on:
      - db

  db:
    image: postgres:10.4-alpine
    volumes:
        - db_data:/var/lib/postgresql/data    # ボリュームなので`./`をつけない
    restart: always
    env_file: ./db/.env.db
    ports:
      - "5432:5432"

  nginx:
    image: nginx:1.19.1-alpine
    
    volumes:
      - static_volume:/usr/share/nginx/html/static/
      - media_volume:/usr/share/nginx/html/media/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - "7000:80"
    depends_on:
      - web

volumes:
  db_data:
  static_volume:
  media_volume: